### ISSUE TITLE
example usage?

### ISSUE THREAD

**Issue by end-user** [dmitry-cherkas/intellij-xslfo-support#2]
I'm trying to use this plugin in IntelliJ 2016, and I would love to see some examples on how to use it.  For example, the build config specifies an `XSLT script file`, but it appears that it's very explicit in what it's looking for - I can't specify a `.fo` file, for example.  How would I go about using this plugin?

**Comment by dmitry-cherkas** [comment]
Hi, @end-user,
You  are right, the plugin is very straight-forward. Currently it only supports XSLT -> PDF transformations with Apache FOP. Run configuration, provided by the plugin takes XSLT file as input, it does not support taking FO files as input currently.

**Comment by dmitry-cherkas** [comment]
And finally, usage examples were added, thanks to @SingingBush!
