### ISSUE TITLE
if user config not specified, call uses jre path

### ISSUE THREAD

**Issue by end-user** [dmitry-cherkas/intellij-xslfo-support#3]
When I left off the "User configuration file (optional)" under `Settings`, the path used `fop.bat -c "C:/Program Files/Java/current/jre/bin"`.  Also, the dialog expects a specific file extension (since it doesn't display anything when I browse folders).

**Comment by dmitry-cherkas** [comment]
Thanks for raising this, I'll provide a fix.

> Also, the dialog expects a specific file extension (since it doesn't display anything when I browse folders).

yes, it expects XML file (userconfig.xml)
